on: [push, pull_request]

jobs:
  armv6_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build on buster armv6
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: armv6
          distro: buster

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          install: |
            apt-get update -q -y
            apt-get install  -q -y openjdk-8-jdk
            apt-get install  -q -y clang
            apt-get install  -q -y gcc

          run: |
            ./gradlew assemble

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: app/build/exe/main/debug
