on: [push, pull_request]

jobs:
  armv6_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    name: Build on ubuntu-20.04 armv6
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: build
        with:
          arch: armv6
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          #githubToken: ${{ github.token }}

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            ./gradlew assemble

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: artifacts
            path: app/build/exe/main/debug
